import logging

from config.settings import (
    DAILY_CANDLE_LIMIT,
    DAILY_INTERVAL,
    ENTRY_CANDLE_LIMIT,
    ENTRY_INTERVAL,
    SWING_SIGNAL_WINDOW_HOURS,
)
from database.db import init_db
from services.binance_service import BinanceService
from services.log_service import add_log
from services.signal_service import SignalService
from services.telegram_service import TelegramService
from strategies.swing_long_v3 import STRATEGY_ID as SWING_STRATEGY_ID
from strategies.swing_long_v3 import evaluate_swing_long_v3


logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s - %(message)s",
)
logger = logging.getLogger(__name__)

ACTIVE_SYMBOL = "BTCUSDT"


def run_scanner() -> None:
    init_db()
    binance = BinanceService()
    signals = SignalService()
    telegram = TelegramService()

    logger.info("Starting BTC swing scanner for %s on %s.", ACTIVE_SYMBOL, ENTRY_INTERVAL)
    add_log(
        "scanner started",
        f"Scanning {ACTIVE_SYMBOL} with {SWING_STRATEGY_ID} on {ENTRY_INTERVAL}. Scalping and alt pairs disabled.",
        "info",
        ACTIVE_SYMBOL,
    )

    try:
        if signals.has_recent_active_signal(ACTIVE_SYMBOL, SWING_STRATEGY_ID, SWING_SIGNAL_WINDOW_HOURS):
            logger.info(
                "%s skipped because a recent active swing signal exists inside %sh.",
                ACTIVE_SYMBOL,
                SWING_SIGNAL_WINDOW_HOURS,
            )
            add_log(
                "signals skipped",
                f"Recent active BTC swing signal already exists inside {SWING_SIGNAL_WINDOW_HOURS}h.",
                "warning",
                ACTIVE_SYMBOL,
            )
            return

        daily_df = binance.get_klines(ACTIVE_SYMBOL, DAILY_INTERVAL, DAILY_CANDLE_LIMIT)
        entry_df = binance.get_klines(ACTIVE_SYMBOL, ENTRY_INTERVAL, ENTRY_CANDLE_LIMIT)
        signal = evaluate_swing_long_v3(ACTIVE_SYMBOL, daily_df, entry_df)

        if signal is None:
            logger.info("%s swing skipped because strategy conditions were not met.", ACTIVE_SYMBOL)
            add_log("skipped conditions", "BTC professional swing conditions were not fully met.", "warning", ACTIVE_SYMBOL)
            return

        signal_id = signals.create_signal(signal)
        telegram.send_message(signals.format_telegram_message(signal))
        logger.info("Signal %s generated for %s using %s.", signal_id, ACTIVE_SYMBOL, SWING_STRATEGY_ID)
        add_log("signal detected", f"Signal {signal_id} generated by {SWING_STRATEGY_ID}.", "success", ACTIVE_SYMBOL)
    except Exception as exc:
        logger.exception("BTC swing scanner failed: %s", exc)
        add_log("scanner error", f"{SWING_STRATEGY_ID}: {exc}", "error", ACTIVE_SYMBOL)
    finally:
        logger.info("Scanner finished.")
        add_log("scanner finished", "BTC swing scanner cycle completed.", "success", ACTIVE_SYMBOL)


if __name__ == "__main__":
    run_scanner()
