import logging

from config.settings import (
    DAILY_CANDLE_LIMIT,
    DAILY_INTERVAL,
    SYMBOLS,
)
from database.db import init_db
from services.log_service import add_log
from services.signal_service import SignalService
from services.telegram_service import TelegramService
from services.twelvedata_service import TwelveDataService
from strategies.smc_v1 import MAX_SIGNALS_PER_MONTH
from strategies.smc_v1 import STRATEGY_ID as ACTIVE_STRATEGY_ID
from strategies.smc_v1 import TIMEFRAME
from strategies.smc_v1 import evaluate_smc_v1


logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s - %(message)s",
)
logger = logging.getLogger(__name__)


def run_scanner() -> None:
    init_db()
    binance = TwelveDataService()
    signals = SignalService()
    telegram = TelegramService()

    logger.info("Starting SMC V1 scanner for %s on %s.", ", ".join(SYMBOLS), TIMEFRAME)
    add_log(
        "scanner started",
        f"Scanning {', '.join(SYMBOLS)} with {ACTIVE_STRATEGY_ID} on {TIMEFRAME}. LONG only.",
        "info",
        "MULTI",
    )

    for symbol in SYMBOLS:
        _process_symbol(symbol, binance, signals, telegram)

    logger.info("Scanner finished.")
    add_log("scanner finished", "SMC V1 scanner cycle completed for all symbols.", "success", "MULTI")


def _process_symbol(
    symbol: str,
    binance: TwelveDataService,
    signals: SignalService,
    telegram: TelegramService,
) -> None:
    logger.info("Processing %s with %s on %s.", symbol, ACTIVE_STRATEGY_ID, TIMEFRAME)
    add_log(
        "symbol started",
        f"Processing {symbol} with {ACTIVE_STRATEGY_ID} on {TIMEFRAME}.",
        "info",
        symbol,
    )

    try:
        if signals.has_recent_active_signal(symbol, ACTIVE_STRATEGY_ID, 24 * 365):
            add_log(
                "signals skipped",
                f"Active duplicate exists for {symbol} and {ACTIVE_STRATEGY_ID}.",
                "warning",
                symbol,
            )
            return

        signals_this_month = signals.count_signals_this_month(symbol, ACTIVE_STRATEGY_ID)
        if signals_this_month >= MAX_SIGNALS_PER_MONTH:
            logger.info(
                "%s skipped because %s signals already exist this month for %s.",
                symbol,
                signals_this_month,
                ACTIVE_STRATEGY_ID,
            )
            add_log(
                "signals skipped",
                f"Monthly cap reached for {ACTIVE_STRATEGY_ID}: {signals_this_month}/{MAX_SIGNALS_PER_MONTH}.",
                "warning",
                symbol,
            )
            return

        daily_df = binance.get_klines(symbol, DAILY_INTERVAL, DAILY_CANDLE_LIMIT)
        entry_df = binance.get_klines(symbol, TIMEFRAME, 180)
        signal = evaluate_smc_v1(symbol, daily_df, entry_df)

        if signal is None:
            logger.info("%s SMC V1 skipped because LONG conditions were not met.", symbol)
            add_log("skipped conditions", "SMC V1 conditions were not met.", "warning", symbol)
            return

        signal_id = signals.create_signal(signal)
        telegram.send_message(signals.format_telegram_message(signal))
        logger.info("Signal %s generated for %s using %s.", signal_id, symbol, ACTIVE_STRATEGY_ID)
        add_log("signal detected", f"Signal {signal_id} generated by {ACTIVE_STRATEGY_ID}.", "success", symbol)
    except Exception as exc:
        logger.exception("SMC V1 scanner failed for %s: %s", symbol, exc)
        add_log("scanner error", f"{ACTIVE_STRATEGY_ID}: {exc}", "error", symbol)


if __name__ == "__main__":
    run_scanner()
